# Change these first
owner: VoisinsVigilants # Your GitHub organization or username, where this repository lives
repo: upptime_production # The name of this repository

sites:
  - name: Site Voisins Vigilants et Solidaires (PROD)
    url: https://app.voisinsvigilantsa.org
  - name: B2B - Voisins Vigilants Connect (PROD)
    url: https://voisinsvigilants-connect.org
  - name: Hodatis (Staging)
    url: https://hodatis.com
  - name: Api B2C - Api Voisins Vigilants (PROD)
    url: api-flutter.voisinsvigilants.org
    check: "tcp-ping"
  - name: Web B2C - Voisins Vigilants (PROD)
    url: https://app.voisinsvigilants.org
  - name: Data - Voisins Vigilants Data (PROD)
    url: https://voisinsvigilants-data.org/
  - name: Territoire - Territoire Vigilant (PROD)
    url: https://territoirevigilant.org

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: upptime_production
  logoUrl: https://firebasestorage.googleapis.com/v0/b/voisins-vigilants.appspot.com/o/asset%2Flogo_vvs_vertical.svg?alt=media&token=b8b44c73-41e0-4584-bce2-c549b5585bcc
  name: Voisins Vigilants Production
  introTitle: "**Voisins Vigilants et Solidaires** environnement de Production"
  introMessage: Page de status des applications de la société Voisins Vigilants et Solidaires®
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
